# This action is centrally managed in https://github.com/asyncapi/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo

# This workflow is designed to work with:
# - autoapprove and automerge workflows for dependabot and asyncapibot.
# - special release branches that we from time to time create in upstream repos. If we open up PRs for them from the very beginning of the release, the release branch will constantly update with new things from the destination branch they are opened against

# It uses GitHub Action that auto-updates pull requests branches, whenever changes are pushed to their destination branch.
# Autoupdating to latest destination branch works only in the context of upstream repo and not forks

name: autoupdate

on:
  push:
    branches-ignore:  
      - 'version-bump/**'
      - 'dependabot/**'
      - 'bot/**'
      - 'all-contributors/**'

jobs:
  autoupdate-for-bot:
    name: Autoupdate autoapproved PR created in the upstream
    runs-on: ubuntu-latest
    steps:
      - name: Autoupdating
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GH_TOKEN_BOT_EVE }}'
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          PR_READY_STATE: "ready_for_review"
          MERGE_CONFLICT_ACTION: "ignore"
